[project]
name = "super-resolution"
version = "0.1.0"
description = "Image Upscaler application using image_gen_aux and Gradio"
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
    "torch==2.14.0+cu126",
    "torchvision==0.29.0+cu126",
    "image_gen_aux @ git+https://github.com/asomoza/image_gen_aux",
    "gradio==6.27.0",
    "requests==2.34.2",
    "huggingface-hub",
]

[[tool.uv.index]]
name = "torch-cuda"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "torch-cuda" }]
torchvision = [{ index = "torch-cuda" }]
